"""Envelope encryption using AWS KMS + AES-256-GCM.

Each field is encrypted with a unique data key generated by KMS. The
encrypted data key is stored alongside the ciphertext so decryption
only requires KMS Decrypt permission on the CMK.

Storage format (base64-encoded JSON):
    {
        "v": 1,
        "key": "<base64 encrypted data key>",
        "iv": "<base64 12-byte nonce>",
        "ct": "<base64 ciphertext + 16-byte GCM tag>"
    }

The entire JSON is then base64-encoded into a single string for DynamoDB
storage (type S).

Design decisions:
- AES-256-GCM provides authenticated encryption (confidentiality + integrity).
- Per-field unique data key limits blast radius of a single key compromise.
- KMS GenerateDataKey is called on every encrypt; Decrypt on every decrypt.
  For 300 employees this is ~600 KMS calls per full table read — well within
  KMS rate limits (30,000 requests/sec shared quota per account).
- Caching data keys would reduce KMS calls but increases complexity and
  key exposure window. For this scale, per-field keys are acceptable.

Project principle 19(b): No fallback. Encryption/decryption failures raise.
"""

from __future__ import annotations

import base64
import json
import os
import secrets
from typing import Any

import boto3
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

# KMS CMK ARN is injected via environment variable.
_KMS_KEY_ARN = os.environ.get("FIELD_ENCRYPTION_KMS_KEY_ARN", "")
_KMS_CLIENT: Any = None

# Encryption format version
_FORMAT_VERSION = 1
_NONCE_BYTES = 12  # 96-bit nonce for GCM


def _get_kms_client() -> Any:
    """Lazy-init KMS client (for Lambda cold start optimization)."""
    global _KMS_CLIENT  # noqa: PLW0603
    if _KMS_CLIENT is None:
        _KMS_CLIENT = boto3.client("kms")
    return _KMS_CLIENT


def encrypt_field(plaintext: str) -> str:
    """Encrypt a plaintext string field using envelope encryption.

    Args:
        plaintext: The sensitive value to encrypt.

    Returns:
        A base64-encoded string containing the encrypted envelope.

    Raises:
        ValueError: If KMS key ARN is not configured.
        botocore.exceptions.ClientError: On KMS API failure.
    """
    if not _KMS_KEY_ARN:
        raise ValueError(
            "FIELD_ENCRYPTION_KMS_KEY_ARN environment variable is required"
        )
    if not plaintext:
        return ""

    kms = _get_kms_client()

    # Generate a unique data key for this field
    dk_response = kms.generate_data_key(
        KeyId=_KMS_KEY_ARN,
        KeySpec="AES_256",
    )
    plaintext_key: bytes = dk_response["Plaintext"]
    encrypted_key: bytes = dk_response["CiphertextBlob"]

    # Encrypt with AES-256-GCM
    nonce = secrets.token_bytes(_NONCE_BYTES)
    aesgcm = AESGCM(plaintext_key)
    ciphertext = aesgcm.encrypt(nonce, plaintext.encode("utf-8"), None)

    # Package into envelope
    envelope = {
        "v": _FORMAT_VERSION,
        "key": base64.b64encode(encrypted_key).decode("ascii"),
        "iv": base64.b64encode(nonce).decode("ascii"),
        "ct": base64.b64encode(ciphertext).decode("ascii"),
    }
    return base64.b64encode(
        json.dumps(envelope, separators=(",", ":")).encode("utf-8")
    ).decode("ascii")


def decrypt_field(encrypted_value: str) -> str:
    """Decrypt an envelope-encrypted field value.

    Args:
        encrypted_value: The base64-encoded envelope string from DynamoDB.

    Returns:
        The original plaintext string.

    Raises:
        ValueError: On malformed envelope or decryption failure.
        botocore.exceptions.ClientError: On KMS API failure.
    """
    if not encrypted_value:
        return ""

    kms = _get_kms_client()

    # Decode envelope
    try:
        envelope_json = base64.b64decode(encrypted_value)
        envelope: dict[str, Any] = json.loads(envelope_json)
    except (ValueError, json.JSONDecodeError) as exc:
        raise ValueError(f"Malformed encrypted envelope: {exc}") from exc

    version = envelope.get("v")
    if version != _FORMAT_VERSION:
        raise ValueError(f"Unsupported envelope version: {version}")

    encrypted_key = base64.b64decode(envelope["key"])
    nonce = base64.b64decode(envelope["iv"])
    ciphertext = base64.b64decode(envelope["ct"])

    # Decrypt the data key via KMS
    dk_response = kms.decrypt(CiphertextBlob=encrypted_key)
    plaintext_key: bytes = dk_response["Plaintext"]

    # Decrypt the field value
    aesgcm = AESGCM(plaintext_key)
    plaintext_bytes = aesgcm.decrypt(nonce, ciphertext, None)
    return plaintext_bytes.decode("utf-8")
